"""
Nano Banana Pro Image Generator

Generate images using Google's Nano Banana Pro (Gemini) or Imagen 3 via Vertex AI.
"""

import os
import base64
from pathlib import Path
from typing import Optional

import vertexai
from vertexai.preview.vision_models import ImageGenerationModel
from vertexai.generative_models import GenerativeModel, GenerationConfig

from .utils import get_env_or_default, ensure_directory


class ImageGenerator:
    """
    Generate images from text prompts using Google's image generation models.
    
    Supports:
    - Nano Banana Pro (Gemini 3 Pro with native image generation)
    - Imagen 3 (fallback)
    """
    
    def __init__(
        self,
        project_id: Optional[str] = None,
        region: str = "us-central1",
        prefer_nano_banana: bool = True
    ):
        """
        Initialize the image generator.
        
        Args:
            project_id: Google Cloud project ID (uses env var if not provided)
            region: Google Cloud region
            prefer_nano_banana: Try Nano Banana Pro first if True
        """
        self.project_id = project_id or get_env_or_default(
            "GCP_PROJECT_ID", 
            "gen-lang-client-0680575763"
        )
        self.region = region
        self.prefer_nano_banana = prefer_nano_banana
        self._initialized = False
    
    def _init_vertex_ai(self) -> None:
        """Initialize Vertex AI SDK."""
        if not self._initialized:
            vertexai.init(project=self.project_id, location=self.region)
            self._initialized = True
    
    def generate_with_nano_banana(
        self, 
        prompt: str, 
        output_path: str
    ) -> bool:
        """
        Generate image using Nano Banana Pro (Gemini with image generation).
        
        Args:
            prompt: Text description of the image
            output_path: Path to save the generated image
            
        Returns:
            True if successful, False if model not available
        """
        try:
            print("🎨 Attempting Nano Banana Pro (Gemini 3 Pro Image)...")
            
            model = GenerativeModel("gemini-3.0-pro-vision")
            
            response = model.generate_content(
                contents=[f"Generate a high-quality, detailed image of: {prompt}"],
                generation_config=GenerationConfig(
                    temperature=0.8,
                    max_output_tokens=8192,
                )
            )
            
            if response.candidates and response.candidates[0].content.parts:
                for part in response.candidates[0].content.parts:
                    if hasattr(part, 'inline_data') and part.inline_data:
                        image_data = base64.b64decode(part.inline_data.data)
                        ensure_directory(str(Path(output_path).parent))
                        with open(output_path, "wb") as f:
                            f.write(image_data)
                        print(f"   ✅ Generated with Nano Banana Pro: {output_path}")
                        return True
            
            print("   ⚠️ Nano Banana Pro did not return an image")
            return False
            
        except Exception as e:
            print(f"   ⚠️ Nano Banana Pro not available: {e}")
            return False
    
    def generate_with_imagen(
        self, 
        prompt: str, 
        output_path: str,
        aspect_ratio: str = "1:1"
    ) -> None:
        """
        Generate image using Imagen 3.
        
        Args:
            prompt: Text description of the image
            output_path: Path to save the generated image
            aspect_ratio: Image aspect ratio (1:1, 16:9, 9:16, 4:3, 3:4)
        """
        print("🎨 Using Imagen 3...")
        
        model = ImageGenerationModel.from_pretrained("imagen-3.0-generate-002")
        
        response = model.generate_images(
            prompt=prompt,
            number_of_images=1,
            aspect_ratio=aspect_ratio,
            safety_filter_level="block_few",
            person_generation="allow_adult",
        )
        
        if response.images:
            ensure_directory(str(Path(output_path).parent))
            response.images[0].save(output_path)
            print(f"   ✅ Generated with Imagen 3: {output_path}")
        else:
            raise RuntimeError("No images generated by Imagen 3")
    
    def generate(
        self,
        prompt: str,
        output_path: str,
        aspect_ratio: str = "1:1"
    ) -> str:
        """
        Generate an image from a text prompt.
        
        Args:
            prompt: Text description of the image
            output_path: Path to save the generated image
            aspect_ratio: Image aspect ratio for Imagen fallback
            
        Returns:
            Path to the generated image
        """
        self._init_vertex_ai()
        
        # Try Nano Banana Pro first if preferred
        if self.prefer_nano_banana:
            if self.generate_with_nano_banana(prompt, output_path):
                return output_path
        
        # Fall back to Imagen 3
        self.generate_with_imagen(prompt, output_path, aspect_ratio)
        return output_path


def main():
    """CLI entry point for image generation."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Generate images with Nano Banana Pro / Imagen 3"
    )
    parser.add_argument("--prompt", required=True, help="Text prompt")
    parser.add_argument("--output", default="generated_image.png", help="Output path")
    parser.add_argument("--project", help="GCP project ID")
    parser.add_argument("--region", default="us-central1", help="GCP region")
    parser.add_argument(
        "--aspect-ratio", 
        default="1:1", 
        choices=["1:1", "16:9", "9:16", "4:3", "3:4"]
    )
    parser.add_argument(
        "--no-nano-banana", 
        action="store_true", 
        help="Skip Nano Banana Pro"
    )
    
    args = parser.parse_args()
    
    print(f"""
╔══════════════════════════════════════════════════════════╗
║          Imagen Apex - Image Generation                  ║
╚══════════════════════════════════════════════════════════╝
""")
    
    generator = ImageGenerator(
        project_id=args.project,
        region=args.region,
        prefer_nano_banana=not args.no_nano_banana
    )
    
    output_path = generator.generate(
        prompt=args.prompt,
        output_path=args.output,
        aspect_ratio=args.aspect_ratio
    )
    
    print(f"\n✅ Image saved to: {output_path}")


if __name__ == "__main__":
    main()
